name: Daily Stock Fetch

on:
  schedule:
    - cron: "0 13 * * *"   # Runs every day at 1 PM UTC
  workflow_dispatch:       # Allows manual run from GitHub UI

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run script
        run: python src/extract.py
